fragment ArticleParts on Article {
  title
  description
  publishedAt
  blocks {
    __typename
    ... on ArticleBlocksRichText {
      body
    }
    ... on ArticleBlocksMedia {
      file
    }
    ... on ArticleBlocksCode {
      content
      lang
    }
  }
}

fragment HeaderParts on Header {
  title
  subtitle
}
